CREATE TABLE TB_GA_TIPO_USUARIO
(
    ID_TIPO_USUARIO NUMBER,
    DESCRIPCION VARCHAR2(100)
);  

ALTER TABLE TB_GA_TIPO_USUARIO ADD CONSTRAINT "PK_ID_TIPO_USUARIO" PRIMARY KEY (ID_TIPO_USUARIO);


CREATE TABLE TB_GA_USUARIO_ESTANDAR
(
    ID_USUARIO_ESTANDAR NUMBER,
    DESCRIPCION VARCHAR2(100)
);

ALTER TABLE TB_GA_USUARIO_ESTANDAR ADD CONSTRAINT "PK_ID_USUARIO_ESTANDAR" PRIMARY KEY (ID_USUARIO_ESTANDAR);


CREATE TABLE TB_GA_TIPO_PASS
(
    ID_TIPO_PASS NUMBER,
    DESCRIPCION VARCHAR2(100)
);


ALTER TABLE TB_GA_TIPO_PASS ADD CONSTRAINT "PK_ID_TIPO_PASS" PRIMARY KEY (ID_TIPO_PASS);

CREATE TABLE TB_GA_SISTEMA
(
ID_SISTEMA NUMBER,
PAIS VARCHAR2(10),
CODIGO_CMDB VARCHAR2(100),
DBNAME VARCHAR2(50),
NOMBRE_CORTO VARCHAR2(100),
NOMBRE_COMPLETO VARCHAR2(200),
USUARIO_ESTANDAR NUMBER,
TIPO_USUARIO NUMBER,
TIPO_PASS NUMBER,
ESTADO NUMBER,
URLSISTEMA VARCHAR2(500)
);

ALTER TABLE TB_GA_SISTEMA ADD CONSTRAINT "PK_ID_SISTEMA" PRIMARY KEY (ID_SISTEMA);

ALTER TABLE TB_GA_SISTEMA ADD CONSTRAINT "PK_SISTEMA_USUARIO_ESTANDAR" FOREIGN KEY (USUARIO_ESTANDAR) REFERENCES TB_GA_USUARIO_ESTANDAR(ID_USUARIO_ESTANDAR) ;
ALTER TABLE TB_GA_SISTEMA ADD CONSTRAINT "PK_SISTEMA_TIPO_USUARIO" FOREIGN KEY (TIPO_USUARIO) REFERENCES TB_GA_TIPO_USUARIO(ID_TIPO_USUARIO) ;
ALTER TABLE TB_GA_SISTEMA ADD CONSTRAINT "PK_SISTEMA_TIPO_PASS" FOREIGN KEY (TIPO_PASS) REFERENCES TB_GA_TIPO_PASS(ID_TIPO_PASS) ;



